// AUTO-GENERATED by scripts/gen-retail-layers.mjs — 직접 수정하지 마세요.
// 체인 데이터 갱신 후 `node scripts/gen-retail-layers.mjs` 로 재생성.
// 레이어 메타데이터(색상·그룹·순서)는 ./retail-layers.ts 참고.

export const RETAIL_LAYER_COUNTS: Record<string, number> = {
  lotte: 30,
  hyundai: 13,
  shinsegae: 10,
  ak: 3,
  galleria: 6,
  artbox: 203,
  abcmart: 322,
  "8seconds": 78,
  spao: 184,
  mixxo: 55,
  daiso: 1714,
  oliveyoung: 1363,
  modernhouse: 143,
  muji: 46,
  hanssem: 22,
  livart: 92,
  iloom: 92,
  nitori: 6,
  uniqlo: 153,
  entersix: 6,
  moda: 17,
  savezone: 9,
  lf: 3,
  emart: 127,
  lottemart: 110,
  hanaromart: 155,
};
